{
 "title": "Groceries - By Category",
 "time": { "from": "2026-02-18T23:15:16.413Z", "to": "2026-02-19T23:15:16.413Z" },
 "panels": [
  {
   "title": "bakery & grains",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grocery",
     "rawSql": "SELECT\n   category,\n   SUM(price) AS \"total\"\nFROM groceries\nWHERE top_category = 'bakery & grains'\nGROUP BY category;\n"
    }
   ]
  },
  {
   "title": "breakfast",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grocery",
     "rawSql": "SELECT\n   category,\n   SUM(price) AS \"total\"\nFROM groceries\nWHERE top_category = 'breakfast'\nGROUP BY category;\n"
    }
   ]
  },
  {
   "title": "dairy & eggs",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grocery",
     "rawSql": "SELECT\n   category,\n   SUM(price) AS \"total\"\nFROM groceries\nWHERE top_category = 'dairy & eggs'\nGROUP BY category;\n"
    }
   ]
  },
  {
   "title": "drinks",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grocery",
     "rawSql": "SELECT\n   category,\n   SUM(price) AS \"total\"\nFROM groceries\nWHERE top_category = 'drinks'\nGROUP BY category;\n"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grocery",
     "rawSql": "SELECT\n   category,\n   SUM(price) AS \"total\"\nFROM groceries\nWHERE top_category = 'fresh food'\nGROUP BY category;\n"
    }
   ]
  },
  {
   "title": "household",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grocery",
     "rawSql": "SELECT\n   category,\n   SUM(price) AS \"total\"\nFROM groceries\nWHERE top_category = 'household'\nGROUP BY category;\n"
    }
   ]
  },
  {
   "title": "pantry",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grocery",
     "rawSql": "SELECT\n   category,\n   SUM(price) AS \"total\"\nFROM groceries\nWHERE top_category = 'pantry'\nGROUP BY category;\n"
    }
   ]
  },
  {
   "title": "personal care",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grocery",
     "rawSql": "SELECT\n   category,\n   SUM(price) AS \"total\"\nFROM groceries\nWHERE top_category = 'personal care'\nGROUP BY category;\n"
    }
   ]
  },
  {
   "title": "pets",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grocery",
     "rawSql": "SELECT\n   category,\n   SUM(price) AS \"total\"\nFROM groceries\nWHERE top_category = 'pets'\nGROUP BY category;\n"
    }
   ]
  },
  {
   "title": "protein",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grocery",
     "rawSql": "SELECT\n   category,\n   SUM(price) AS \"total\"\nFROM groceries\nWHERE top_category = 'protein'\nGROUP BY category;\n"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grocery",
     "rawSql": "SELECT\n   category,\n   SUM(price) AS \"total\"\nFROM groceries\nWHERE top_category = 'snacks & sweets'\nGROUP BY category;\n"
    }
   ]
  }
 ]
}